// Katalog planı: pazar yeri verisinden (kaynak/*.json, 3 Ekim 2026) sitedeki ürünlere eşleme.
// Her varyant bir Trendyol ürününe (ty) bağlıdır; görseller ve barkod oradan gelir.
// Fiyat kuralı: Trendyol ve Hepsiburada'daki güncel satış fiyatlarından düşük olanı (fiyat: elle verilmişse o).
// Açıklamalar markanın Hepsiburada metinlerinden kısaltıldı; metni olmayan ürünlerde yalnız
// pazar yerinde doğrulanan bilgiler (ölçü, renk, malzeme, kokusuz vb.) yazıldı.

const MUM_BAKIM = [
  "İlk yakışta mumun yüzeyi tamamen eriyene kadar (2-3 saat) söndürmeyin; ortada çukurlaşma olmaz.",
  "Her yakıştan önce fitili 4-5 mm kısaltın.",
  "Hava akımı olan yerlerden, perde ve kâğıt gibi kolay tutuşan nesnelerden uzak tutun.",
  "Isıya dayanıklı bir yüzeyde yakın, yanarken gözetimsiz bırakmayın.",
  "Mumlar arasında 5-10 cm boşluk bırakın; çocuk ve evcil hayvanlardan uzak tutun.",
];
const AHSAP_BAKIM = [
  "Nemli bezle silin, hemen kurulayın.",
  "Bulaşık makinesinde yıkamayın, suda bekletmeyin.",
];
const SERAMIK_BAKIM = ["Kuru ya da hafif nemli bezle silin.", "Aşındırıcı temizleyici kullanmayın."];
const CAM_BAKIM = ["Elde, yumuşak süngerle yıkayın.", "Ani sıcaklık değişiminden koruyun."];
const BOROSILIKAT_BAKIM = ["Elde yıkanmalıdır.", "Yağ değişiminde iyice kurutup yeniden doldurun."];

export const KATEGORILER = [
  {
    slug: "vazo-obje",
    ad: "Vazo & Obje",
    ozet: "Cam kapaklı bonbon vazolar, el yapımı seramikler ve heykelsi objeler.",
  },
  {
    slug: "mum",
    ad: "Mum",
    ozet: "Kokusuz top mumlar, şamdan mumları ve figürlü dekoratif mumlar.",
  },
  {
    slug: "sunum-servis",
    ad: "Sunum & Servis",
    ozet: "Mango ağacından emaye kaplamalı tabaklar, sunum tahtaları ve ceviz kesme tahtaları.",
  },
  {
    slug: "mutfak",
    ad: "Mutfak",
    ozet: "Borosilikat cam yağdanlıklar ve mutfak yardımcıları.",
  },
  {
    slug: "banyo",
    ad: "Banyo",
    ozet: "Seramik sıvı sabunluklar.",
  },
];

export const KOLEKSIYONLAR = [
  {
    slug: "bonbon-serisi",
    ad: "Bonbon serisi",
    ozet: "Şeker renkli kapaklarıyla iki parçalı cam vazolar. Çiçeksiz de tamamlanmış görünür.",
  },
  {
    slug: "yesil-ekose",
    ad: "Yeşil ekose",
    ozet: "Mango ağacı çerçeve, yeşil kareli emaye iç yüzey. Kahvaltı sofrasının en sevilen deseni.",
  },
  {
    slug: "yeni-yil-sofrasi",
    ad: "Yeni yıl sofrası",
    ozet: "Kar tanesi, çam ağacı ve kurabiye adam formlu tabaklar, altın yaldızlı mumlar.",
  },
  {
    slug: "heykelsi-seramikler",
    ad: "Heykelsi seramikler",
    ozet: "Mat beyaz ve siyah gövdeler, hardal kulplar, oval boşluklar. Rafta tek başına duran parçalar.",
  },
];

export const URUNLER = [
  // ───────────────────────── Vazo & Obje ─────────────────────────
  {
    slug: "soft-cool-bonbon-vazo",
    ad: "Soft Cool Bonbon Vazo",
    marka: "zensori",
    kategori: "vazo-obje",
    koleksiyonlar: ["bonbon-serisi"],
    hb: "HBC0000CYCC85",
    ozet: "Buz mavisi cam gövde, sarı kapak. Bonbon serisinin en küçüğü.",
    aciklama: [
      "Bonbon serisinin en küçük parçası iki ayrı camdan oluşur: buz mavisi bir gövde ve onun üstüne oturan yuvarlak, sarı bir kapak. Kapağı kaldırınca küçük bir saklama kabı, kapalıyken rafta duran bir obje.",
      "Pastel tonlu bir duvarın önünde, kitapların yanında ya da giriş konsolunda tek başına durur. Kuru bir dal için de uygundur.",
    ],
    ozellikler: [["Malzeme", "Cam"], ["Yükseklik", "14 cm"], ["Parça", "Gövde ve kapak"]],
    bakim: CAM_BAKIM,
    secenekler: ["renk"],
    varyantlar: [{ ty: 1106986345, renk: "Mavi", fiyat: 1599 }],
  },
  {
    slug: "dramatic-cool-bonbon-vazo",
    ad: "Dramatic Cool Bonbon Vazo",
    marka: "zensori",
    kategori: "vazo-obje",
    koleksiyonlar: ["bonbon-serisi"],
    hb: "HBC0000CYB91O",
    ozet: "Çift gövdeli, kapaklı cam vazo. Lila kapak, krem gövde.",
    aciklama: [
      "Çift gövdeli formu, iki farklı renk tonunu üst üste koyar. Pastel tonlardaki şeffaf yüzey ışığı yansıtır, rafa ferahlık katar.",
      "Kapaklı yapısı sayesinde hem dekoratif bir obje hem de küçük bir saklama kabıdır. Zen felsefesinden ilham alan formu, tek başına sergilendiğinde de çiçeklerle de dengeli durur.",
    ],
    ozellikler: [["Malzeme", "Cam"], ["Ölçü", "12 × 12 × 17 cm"], ["Parça", "Gövde ve kapak"]],
    bakim: CAM_BAKIM,
    secenekler: ["renk"],
    varyantlar: [{ ty: 1106981619, renk: "Krem", fiyat: 1599 }],
  },
  {
    slug: "istanbul-bonbon-vazo",
    ad: "İstanbul Bonbon Vazo",
    marka: "zensori",
    kategori: "vazo-obje",
    koleksiyonlar: ["bonbon-serisi"],
    hb: "HBC0000CYBDHJ",
    ozet: "Sıcak toprak tonlu gövde, yumuşak mor kapak. Organik hatlı cam vazo.",
    aciklama: [
      "Alt bölümdeki sıcak ton, üstteki yumuşak morla buluşur ve dengeli bir kontrast kurar. Organik hatları ve ışığı yansıtan parlak yüzeyiyle rafta derinlik yaratır.",
      "Raflarda, masalarda ya da sevdiğiniz bir köşede tek başına sergilenir. Markanın kendi sözleriyle: doğal, yalın, uyumlu ve şiirsel.",
    ],
    ozellikler: [["Malzeme", "Cam"], ["Ölçü", "12 × 12 × 20 cm"], ["Parça", "Gövde ve kapak"]],
    bakim: CAM_BAKIM,
    secenekler: ["renk"],
    varyantlar: [{ ty: 1106981395, renk: "Haki", fiyat: 2499 }],
  },
  {
    slug: "trendy-milas-vazo",
    ad: "Trendy Milas Vazo",
    marka: "zensori",
    kategori: "vazo-obje",
    koleksiyonlar: ["bonbon-serisi"],
    hb: "HBC0000CYBNFH",
    ozet: "Mat, buzlu pembe cam gövde ve kahve tonlu kıvrımlı ağız.",
    aciklama: [
      "Yumuşak geçişli pembe tonları ve organik formuyla el işçiliğini hissettiren bir cam vazo. Ağız kısmındaki kahve tonlu kıvrım, sade gövdeye karakter verir.",
      "Doğal ışıkla buluştuğunda yarı saydam yüzey odaya sıcaklık yayar. Kuru ya da taze çiçekle, ya da hiçbir şey koymadan kullanılabilir.",
    ],
    ozellikler: [["Malzeme", "Cam"], ["Yüzey", "Mat, buzlu"], ["Yükseklik", "20 cm"]],
    bakim: CAM_BAKIM,
    secenekler: ["renk"],
    varyantlar: [{ ty: 1107085688, renk: "Pembe", fiyat: 2499 }],
  },
  {
    slug: "boho-ege-bonbon-vazo",
    ad: "Boho Ege Bonbon Vazo",
    marka: "zensori",
    kategori: "vazo-obje",
    koleksiyonlar: ["bonbon-serisi"],
    hb: "HBC0000CYB854",
    ozet: "Lavanta tonlu gövde, canlı turuncu kapak. Serinin en büyüğü.",
    aciklama: [
      "Lavanta tonundaki gövde, canlı turuncu kapağıyla güçlü bir kontrast kurar. Işığın altında parlayan yüzeyi odaya hem enerji hem huzur katar.",
      "Yalnızca bir saklama kabı değil; renklerin dengeli karşıtlığıyla rafın odak noktası olan bir parça.",
    ],
    ozellikler: [["Malzeme", "Cam"], ["Ölçü", "15,5 × 15,5 × 27 cm"], ["Parça", "Gövde ve kapak"]],
    bakim: CAM_BAKIM,
    secenekler: ["renk"],
    varyantlar: [{ ty: 1106961945, renk: "Lavanta", fiyat: 2899 }],
  },
  {
    slug: "el-yapimi-cam-vazo",
    ad: "El Yapımı Cam Vazo",
    marka: "zensori",
    kategori: "vazo-obje",
    koleksiyonlar: [],
    hb: "HBC0000C5NIVZ",
    ozet: "Doğal taş dokusundan ilham alan, krem ve bal tonlu el yapımı cam.",
    aciklama: [
      "Krem ve bal tonlarının yumuşak geçişleri, doğal taş dokusunu hatırlatır. El yapımı üretim nedeniyle her parçanın deseni kendine özgüdür.",
      "Çiçek aranjmanları için uygun olduğu gibi boş haliyle de masada ya da konsolda sakin bir odak noktası oluşturur.",
    ],
    ozellikler: [["Malzeme", "El yapımı cam"], ["Ölçü", "17 × 23 cm"]],
    bakim: CAM_BAKIM,
    secenekler: ["renk"],
    varyantlar: [{ ty: 1081906459, renk: "Bal", fiyat: 3999 }],
  },
  {
    slug: "el-yapimi-cam-kase-vazo",
    ad: "El Yapımı Cam Kase Vazo",
    marka: "zensori",
    kategori: "vazo-obje",
    koleksiyonlar: [],
    ozet: "Geniş ağızlı, krem ve bal tonlu el yapımı cam kase.",
    aciklama: [
      "El Yapımı Cam Vazo ile aynı serinin geniş ağızlı kardeşi. Krem ve bal tonlarındaki akışkan desen, her parçada farklı düşer.",
      "Kısa saplı çiçekler, mevsim meyveleri ya da boş haliyle bir konsolun ortası için.",
    ],
    ozellikler: [["Malzeme", "El yapımı cam"], ["Ölçü", "22 × 16 cm"], ["Form", "Yuvarlak"]],
    bakim: CAM_BAKIM,
    secenekler: ["renk"],
    varyantlar: [{ ty: 1081902968, renk: "Bal", fiyat: 3999 }],
  },
  {
    slug: "kulplu-seramik-vazo",
    ad: "Kulplu Seramik Vazo",
    marka: "zensori",
    kategori: "vazo-obje",
    koleksiyonlar: ["heykelsi-seramikler"],
    hb: "HBC0000C0XWCE",
    hb2: "HBCV0000C0TU7S",
    ozet: "Mat gövde, sıcak renkli tek kulp. El yapımı seramik.",
    aciklama: [
      "Doğal formlardan ilham alan bu vazo, mat gövdesi ve sıcak renkli kulp detayıyla odaya dingin bir hava katar. El yapımı dokusu sayesinde her parça kendine özgüdür.",
      "Heykelsi silueti çiçek aranjmanı için de, tek başına sergilemek için de dengelidir. Krem ve siyah iki rengi var.",
    ],
    ozellikler: [["Malzeme", "El yapımı seramik"], ["Yüzey", "Mat"], ["Ölçü", "12 × 25 cm"]],
    bakim: SERAMIK_BAKIM,
    secenekler: ["renk"],
    varyantlar: [
      { ty: 1081920793, renk: "Krem", fiyat: 1499 },
      { ty: 1081906615, renk: "Siyah", fiyat: 1399 },
    ],
  },
  {
    slug: "modern-tasarimli-seramik-vazo",
    ad: "Modern Tasarımlı Seramik Vazo",
    marka: "zensori",
    kategori: "vazo-obje",
    koleksiyonlar: ["heykelsi-seramikler"],
    hb: "HBC0000C0ZFSQ",
    ozet: "Geniş, geometrik gövde ve iki hardal kulp. Krem ya da siyah.",
    aciklama: [
      "Minimal çizgileri ve renk kontrastıyla öne çıkan bir seramik vazo. Mat gövde ve iki sarı kulp, geometrik siluete sıcaklık katar.",
      "Tek başına sergilenebilir; kuru çiçek ya da dekoratif bir dal ile de kullanılabilir.",
    ],
    ozellikler: [["Malzeme", "El yapımı seramik"], ["Yüzey", "Mat"], ["Ölçü", "18 × 21 cm"]],
    bakim: SERAMIK_BAKIM,
    secenekler: ["renk"],
    varyantlar: [
      { ty: 1080190962, renk: "Krem", fiyat: 1399 },
      { ty: 1081911197, renk: "Siyah", fiyat: 1399 },
    ],
  },
  {
    slug: "heykelsi-form-seramik-vazo",
    ad: "Heykelsi Form Seramik Vazo",
    marka: "zensori",
    kategori: "vazo-obje",
    koleksiyonlar: ["heykelsi-seramikler"],
    ozet: "İnce uzun siyah gövde, boynunda iki hardal halka.",
    aciklama: [
      "İnce, uzun boyunlu bir siyah seramik. Boyundaki iki hardal halka formu ikiye böler ve vazoya heykelsi bir duruş verir.",
      "Tek dal ya da birkaç kuru başakla, yemek masasında veya kitaplıkta dikey bir vurgu.",
    ],
    ozellikler: [["Malzeme", "Seramik"], ["Yüzey", "Mat"], ["Renk", "Siyah gövde, hardal halkalar"]],
    bakim: SERAMIK_BAKIM,
    secenekler: ["renk"],
    varyantlar: [{ ty: 1081910939, renk: "Siyah", fiyat: 1399 }],
  },
  {
    slug: "oval-bosluklu-seramik-vazo",
    ad: "Oval Boşluklu Seramik Vazo",
    marka: "zensori",
    kategori: "vazo-obje",
    koleksiyonlar: ["heykelsi-seramikler"],
    hb: "HBC0000C13QSC",
    ozet: "Pütürlü beyaz yüzey, ortada siyah oval boşluk, iki dikey ağız.",
    aciklama: [
      "Geometrik sadeliğiyle dikkat çeken bu parçada, merkezdeki siyah oval boşluk derinlik ve kontrast yaratır. İki dikey silindir simetrik bir denge kurar; pütürlü beyaz yüzey ışıkla birlikte dokusunu gösterir.",
      "Sehpada, kitaplıkta ya da giriş alanında tek başına bir sanat nesnesi gibi durur.",
    ],
    ozellikler: [["Malzeme", "Seramik"], ["Yüzey", "Pütürlü, mat"], ["Ölçü", "18 × 19 cm"]],
    bakim: SERAMIK_BAKIM,
    secenekler: ["renk"],
    varyantlar: [{ ty: 1081915330, renk: "Beyaz", fiyat: 1599 }],
  },
  {
    slug: "heykelsi-seramik-vazo",
    ad: "Heykelsi Seramik Vazo",
    marka: "zensori",
    kategori: "vazo-obje",
    koleksiyonlar: ["heykelsi-seramikler"],
    hb: "HBC0000C13VFI",
    ozet: "U formlu, ayaklı, pütürlü beyaz seramik vazo.",
    aciklama: [
      "U formlu silueti ve el işçiliğini andıran pütürlü yüzeyiyle sade ama dokunsal bir parça. Pastel bir duvarın önünde dingin bir kontrast kurar.",
      "Boru formundaki iki açıklığa birkaç tüy çiçek ya da kuru dal yerleştirmek yeterli. Salonda, girişte ya da çalışma masasında.",
    ],
    ozellikler: [["Malzeme", "Seramik"], ["Yüzey", "Pütürlü, mat"], ["Ölçü", "20 × 17,5 cm"]],
    bakim: SERAMIK_BAKIM,
    secenekler: ["renk"],
    varyantlar: [{ ty: 1081915762, renk: "Beyaz", fiyat: 1499 }],
  },
  {
    slug: "siyah-konturlu-seramik-vazo",
    ad: "Siyah Konturlu Seramik Vazo",
    marka: "zensori",
    kategori: "vazo-obje",
    koleksiyonlar: ["heykelsi-seramikler"],
    hb: "HBC0000C12OD4",
    ozet: "Mat beyaz gövde, siyah konturlu büyük oval kesitler.",
    aciklama: [
      "Büyük oval kesitleri ve siyah konturlarıyla yüzü andıran soyut bir form. Her kesit ışıkla farklı bir gölge oyunu kurar.",
      "Çiçeksiz de tamamlanmış görünür. Rafta, konsolda ya da yemek masasında tek başına bir odak noktası.",
    ],
    ozellikler: [["Malzeme", "Mat seramik"], ["Renk", "Beyaz gövde, siyah kontur"], ["Ölçü", "19 × 14 cm"]],
    bakim: SERAMIK_BAKIM,
    secenekler: ["renk"],
    varyantlar: [{ ty: 1081912895, renk: "Beyaz", fiyat: 1499 }],
  },
  {
    slug: "heykelsi-seramik-obje",
    ad: "Heykelsi Seramik Obje",
    marka: "zensori",
    kategori: "vazo-obje",
    koleksiyonlar: ["heykelsi-seramikler"],
    ozet: "Küçük, beyaz, siyah halkalı seramik obje. Kuru çiçek için üç ağız.",
    aciklama: [
      "Oval boşluklu serinin küçük boyu. Siyah halkalı bir açıklık ve üç kısa ağız, beyaz seramiğe heykelsi bir yüz verir.",
      "Raf aralarında, kitapların önünde ya da kahvaltı masasında birkaç kuru dal ile.",
    ],
    ozellikler: [["Malzeme", "Seramik"], ["Ölçü", "10 × 10 cm"]],
    bakim: SERAMIK_BAKIM,
    secenekler: ["renk"],
    varyantlar: [{ ty: 1081915294, renk: "Beyaz", fiyat: 1499 }],
  },
  {
    slug: "geometrik-seramik-obje",
    ad: "Geometrik Seramik Obje",
    marka: "zensori",
    kategori: "vazo-obje",
    koleksiyonlar: ["heykelsi-seramikler"],
    ozet: "Ayaklı, yamuk formlu beyaz seramik; ortada altın bir daire.",
    aciklama: [
      "Kısa ayaklar üstünde duran yamuk bir form ve tam ortasında altın tonlu bir daire. Dokulu beyaz yüzey, altın detayı öne çıkarır.",
      "Konsolda, raf ortasında ya da kitapların yanında yatay bir denge unsuru olarak.",
    ],
    ozellikler: [["Malzeme", "Seramik"], ["Ölçü", "23 × 18 cm"]],
    bakim: SERAMIK_BAKIM,
    secenekler: ["renk"],
    varyantlar: [{ ty: 1081917895, renk: "Beyaz", fiyat: 1499 }],
  },

  // ───────────────────────── Mum ─────────────────────────
  {
    slug: "sessiz-kureler-mum",
    ad: "Sessiz Küreler Mum",
    marka: "zensori",
    kategori: "mum",
    koleksiyonlar: ["yeni-yil-sofrasi"],
    ozet: "Kokusuz top mum. Krem, beyaz ve gri; 8 ve 10 cm.",
    aciklama: [
      "Sessiz Küreler koleksiyonunun yalın top mumları. Kokusuzdur; sofrada yemeğin kokusuna karışmaz.",
      "Desenli bir porselen tabağın ortasında, kitaplığın bir rafında ya da birkaç boyu yan yana dizerek kullanın.",
    ],
    ozellikler: [["Koku", "Kokusuz"], ["Boyut", "8 × 8 cm ya da 10 × 10 cm"], ["Menşei", "Türkiye"]],
    bakim: MUM_BAKIM,
    secenekler: ["boyut", "renk"],
    varyantlar: [
      { ty: 1091315825, boyut: "8 cm", renk: "Krem", fiyat: 299 },
      { ty: 1091315759, boyut: "8 cm", renk: "Beyaz", fiyat: 449 },
      { ty: 1091316014, boyut: "8 cm", renk: "Gri", fiyat: 449 },
      { ty: 1091346721, boyut: "10 cm", renk: "Krem", fiyat: 549 },
      { ty: 1091346765, boyut: "10 cm", renk: "Beyaz", fiyat: 549 },
      { ty: 1091346730, boyut: "10 cm", renk: "Gri", fiyat: 549 },
    ],
  },
  {
    slug: "tirtikli-samdan-mum",
    ad: "Tırtıklı Şamdan Mum",
    marka: "zensori",
    kategori: "mum",
    koleksiyonlar: [],
    hb: "HBCV0000CGXBZS",
    ozet: "Katmanlı Sessizlik koleksiyonu. Tırtıklı yüzeyli 25 cm şamdan mumu.",
    aciklama: [
      "Katmanlı Sessizlik koleksiyonunun tırtıklı yüzeyi, ışığın ve gölgenin ritmini mumun üstüne taşır. Silindirik, sade ve karakterli.",
      "Üç ton: beyaz saf ve nötr bir başlangıç, gri düşünceli ve zamansız, vizon sıcak ve toprakla uyumlu. Sade sofralar ve sessiz köşeler için.",
    ],
    ozellikler: [["Ölçü", "2 × 25 cm"], ["Adet", "1"], ["Menşei", "Türkiye"]],
    bakim: MUM_BAKIM,
    secenekler: ["renk"],
    varyantlar: [
      { ty: 1091400365, renk: "Beyaz", fiyat: 399 },
      { ty: 1091400188, renk: "Gri", fiyat: 399 },
      { ty: 1091400403, renk: "Vizon", fiyat: 399 },
    ],
  },
  {
    slug: "ahenk-samdan-mum-dortlu",
    ad: "Ahenk Şamdan Mum, 4 Adet",
    marka: "zensori",
    kategori: "mum",
    koleksiyonlar: ["yeni-yil-sofrasi"],
    hb: "HBCV0000CGH34E",
    ozet: "Düz, el yapımı 25 cm şamdan mumu; dörtlü paket.",
    aciklama: [
      "Yalın formu ve dingin renkleriyle akşam sofralarından okuma köşelerine kadar her yerde sakin bir ışık. Dumanı az, ışığı yumuşak.",
      "Siyah derin ve güçlü, beyaz saf ve aydınlık, krem yumuşak ve doğal. Paket dört mumdan oluşur.",
    ],
    ozellikler: [["Ölçü", "2 × 25 cm"], ["Adet", "4"], ["Üretim", "El yapımı"], ["Menşei", "Türkiye"]],
    bakim: MUM_BAKIM,
    secenekler: ["renk"],
    varyantlar: [
      { ty: 1091304013, renk: "Krem", fiyat: 400 },
      { ty: 1091304022, renk: "Beyaz", fiyat: 400 },
      { ty: 1091304014, renk: "Siyah", fiyat: 400 },
    ],
  },
  {
    slug: "tavus-kusu-desenli-mum",
    ad: "Tavus Kuşu Desenli Mum",
    marka: "zensori",
    kategori: "mum",
    koleksiyonlar: ["yeni-yil-sofrasi"],
    ozet: "Altın tavus kuşu ve yaprak kabartmalı büyük top mum.",
    aciklama: [
      "Krem bir kürenin üzerinde altın tonlu tavus kuşu ve yaprak kabartmaları. Yanmadığında da masanın ortasında bir süs gibi durur.",
      "Kokusuzdur. Bir servis tabağının ya da mumluk tabağının üstünde kullanın.",
    ],
    ozellikler: [["Koku", "Kokusuz"], ["Ölçü", "14 × 13 cm"], ["Menşei", "Türkiye"]],
    bakim: MUM_BAKIM,
    secenekler: ["renk"],
    varyantlar: [{ ty: 1090497834, renk: "Krem", fiyat: 2200 }],
  },
  {
    slug: "dantel-dokunuslu-mum",
    ad: "Dantel Dokunuşlu Dekoratif Mum",
    marka: "zensori",
    kategori: "mum",
    koleksiyonlar: [],
    ozet: "Dantel desenli silindir mum. 15 ve 20 cm.",
    aciklama: [
      "Silindir gövdeyi saran dantel deseni, mumu yanmadığında da bir dekor parçasına çevirir. Şeffaf paket ve rafya kurdeleyle gelir.",
      "Kokusuzdur. Tek başına ya da farklı boylarla gruplayarak kullanın.",
    ],
    ozellikler: [["Koku", "Kokusuz"], ["Ölçü", "10 × 15 cm ya da 10 × 20 cm"], ["Menşei", "Türkiye"]],
    bakim: MUM_BAKIM,
    secenekler: ["boyut", "renk"],
    varyantlar: [
      { ty: 1091220970, boyut: "15 cm", renk: "Gri", fiyat: 1299 },
      { ty: 1091220973, boyut: "15 cm", renk: "Vizon", fiyat: 1299 },
      { ty: 1091237695, boyut: "20 cm", renk: "Gri", fiyat: 1499 },
    ],
  },
  {
    slug: "tuy-kabartmali-silindir-mum",
    ad: "Tüy Kabartmalı Silindir Mum",
    marka: "zensori",
    kategori: "mum",
    koleksiyonlar: [],
    ozet: "Altın tonlu tüy kabartmalı beyaz silindir mum. 10 ve 14 cm.",
    aciklama: [
      "Beyaz gövde üzerinde altın tonlu, ince bir tüy kabartması. Yandığında desen içeriden belirginleşir.",
      "Kokusuzdur; yemek masasında da rahatça kullanılır.",
    ],
    ozellikler: [["Koku", "Kokusuz"], ["Ölçü", "7 × 10 cm ya da 7 × 14 cm"], ["Menşei", "Türkiye"]],
    bakim: MUM_BAKIM,
    secenekler: ["boyut"],
    varyantlar: [
      { ty: 1091562668, boyut: "10 cm", renk: "Altın", fiyat: 599 },
      { ty: 1091563165, boyut: "14 cm", renk: "Altın", fiyat: 749 },
    ],
  },
  {
    slug: "yuzler-tealight-mum",
    ad: "Yüzler Tealight Mum",
    marka: "zensori",
    kategori: "mum",
    koleksiyonlar: [],
    ozet: "İçi boş, yüz kabartmalı mum. İçine tealight konur.",
    aciklama: [
      "Kabartma yüzlerle çevrili, içi boş bir mum. Ortasına bir tealight yerleştirdiğinizde ışık mumun gövdesinden süzülür.",
      "Tealight bittiğinde yenisini koymanız yeterli; dış gövde uzun süre kullanılır.",
    ],
    ozellikler: [["Tür", "Tealight mumluk"], ["Ölçü", "18 × 12 cm"], ["Menşei", "Türkiye"]],
    bakim: MUM_BAKIM,
    secenekler: ["renk"],
    varyantlar: [{ ty: 1090492734, renk: "Krem", fiyat: 1100 }],
  },
  {
    slug: "kaktus-mum",
    ad: "Kaktüs Mum",
    marka: "zensori",
    kategori: "mum",
    koleksiyonlar: [],
    ozet: "Pembe çiçekli küçük kaktüs biçiminde kokusuz mum.",
    aciklama: [
      "Tepesinde pembe bir çiçek açmış yuvarlak bir kaktüs. Rafta, pencere önünde ya da çalışma masasında küçük bir neşe.",
      "Kokusuzdur. Yakmak istemezseniz bir obje olarak da durur.",
    ],
    ozellikler: [["Koku", "Kokusuz"], ["Ölçü", "8 × 8 cm"], ["Menşei", "Türkiye"]],
    bakim: MUM_BAKIM,
    secenekler: ["renk"],
    varyantlar: [{ ty: 1091377648, renk: "Yeşil", fiyat: 649 }],
  },
  {
    slug: "sevimli-kopek-mum",
    ad: "Sevimli Köpek Mum",
    marka: "zensori",
    kategori: "mum",
    koleksiyonlar: [],
    ozet: "Kıvırcık tüylü, kurdeleli oturan köpek figürlü mum.",
    aciklama: [
      "Kıvırcık tüyleri ve boynundaki kurdelesiyle oturan bir köpek. Çocuk odasında ya da bir rafta, yakılmadan da durur.",
      "Kokusuzdur. Krem ve gri olmak üzere iki rengi var.",
    ],
    ozellikler: [["Koku", "Kokusuz"], ["Ölçü", "11 × 16 cm"], ["Menşei", "Türkiye"]],
    bakim: MUM_BAKIM,
    secenekler: ["renk"],
    varyantlar: [
      { ty: 1091560153, renk: "Krem", fiyat: 899 },
      { ty: 1091560190, renk: "Gri", fiyat: 899 },
    ],
  },

  // ───────────────────────── Sunum & Servis ─────────────────────────
  {
    slug: "mango-ekose-oval-sunum-tabagi",
    ad: "Mango Ekose Oval Sunum Tabağı",
    marka: "zensori",
    kategori: "sunum-servis",
    koleksiyonlar: ["yesil-ekose"],
    hb: "HBC0000C1B7L1",
    ozet: "Mango ağacı çerçeve, yeşil ekose emaye iç yüzey. Üç boy.",
    aciklama: [
      "Mango ağacından oval bir tabak; iç yüzeyi yeşil ekose desenli emaye ile kaplı. Yeşilin derin tonu ve ince desen, ahşabın sıcaklığıyla dengelenir.",
      "Küçük boy takı ve anahtar için, orta boy peynir ve zeytin için, büyük boy kahvaltı sunumları için. Sofrayı yormaz.",
    ],
    ozellikler: [["Malzeme", "Mango ağacı, emaye kaplama"], ["Form", "Oval"], ["Ölçü", "20,5 × 10 / 25 × 13 / 30,5 × 15 cm"], ["Menşei", "Hindistan"]],
    bakim: AHSAP_BAKIM,
    secenekler: ["boyut"],
    varyantlar: [
      { ty: 1066285225, boyut: "20 cm", renk: "Yeşil", fiyat: 1100 },
      { ty: 1066279211, boyut: "25 cm", renk: "Yeşil", fiyat: 1299 },
      { ty: 1066254778, boyut: "30 cm", renk: "Yeşil", fiyat: 1499 },
    ],
  },
  {
    slug: "mango-ekose-kare-servis-tabagi",
    ad: "Mango Ekose Kare Servis Tabağı",
    marka: "zensori",
    kategori: "sunum-servis",
    koleksiyonlar: ["yesil-ekose"],
    hb: "HBC0000C1EH15",
    ozet: "Doğal ahşap çerçeveli kare servis tabağı, yeşil kareli iç yüzey.",
    aciklama: [
      "Klasik kare desenin modern bir yorumu. Doğal ahşap çerçeve ile desenli iç yüzeyin birlikteliği, tabağı hem servis hem dekor parçası yapar.",
      "Kahvaltı, ikram ve misafir sofraları için. Keten örtüler ve ahşap mobilyalarla birlikte en iyi halini alır.",
    ],
    ozellikler: [["Malzeme", "Mango ağacı, emaye kaplama"], ["Form", "Kare"], ["Ölçü", "25,5 × 25,5 cm ya da 30 × 30 cm"]],
    bakim: AHSAP_BAKIM,
    secenekler: ["boyut"],
    varyantlar: [
      { ty: 1066294112, boyut: "25 cm", renk: "Yeşil", fiyat: 1499 },
      { ty: 1066268105, boyut: "30 cm", renk: "Yeşil", fiyat: 2429 },
    ],
  },
  {
    slug: "mango-ekose-kalp-tabak",
    ad: "Mango Ekose Kalp Tabak",
    marka: "zensori",
    kategori: "sunum-servis",
    koleksiyonlar: ["yesil-ekose"],
    hb: "HBC0000C1EL68",
    ozet: "Kalp formunda küçük ahşap tabak, yeşil ekose iç yüzey.",
    aciklama: [
      "Kalp formundaki küçük tabağın iç yüzeyindeki yeşil ekose, nostaljik bir sıcaklık taşır. Dış yüzeyde mango ağacının doğal dokusu görünür.",
      "Kuruyemiş, takı ya da küçük objeler için. Sevgi temalı sunumlarda ve hediye kutularında da yer bulur.",
    ],
    ozellikler: [["Malzeme", "Mango ağacı, emaye kaplama"], ["Form", "Kalp"], ["Ölçü", "13 × 14 cm"]],
    bakim: AHSAP_BAKIM,
    secenekler: ["renk"],
    varyantlar: [{ ty: 1066051496, renk: "Yeşil", fiyat: 1099 }],
  },
  {
    slug: "mango-ekose-sapli-sunum-tahtasi",
    ad: "Mango Ekose Saplı Sunum Tahtası",
    marka: "zensori",
    kategori: "sunum-servis",
    koleksiyonlar: ["yesil-ekose"],
    hb: "HBC0000C1C6PH",
    ozet: "İpli saplı mango ağacı tahta; ortası yeşil ekose emaye. İki boy.",
    aciklama: [
      "Doğal mango ağacından bir sunum tahtası. Ortadaki yeşil ekose emaye yüzey sunuma karakter katar, ahşabın sıcak dokusu sofrayı yumuşatır.",
      "İpli sapı sayesinde kullanımdan sonra duvara ya da kancaya asılabilir. Peynir, meze ve küçük ikramlar için. Her parçanın doğal doku ve rengi farklıdır.",
    ],
    ozellikler: [["Malzeme", "Mango ağacı, emaye kaplama"], ["Ölçü", "38 cm ya da 46 × 16 cm"], ["Detay", "İpli kulp"]],
    bakim: AHSAP_BAKIM,
    secenekler: ["boyut"],
    varyantlar: [
      { ty: 1066111346, boyut: "38 cm", renk: "Yeşil", fiyat: 1599 },
      { ty: 1066072137, boyut: "46 cm", renk: "Yeşil", fiyat: 1799 },
    ],
  },
  {
    slug: "cam-agaci-ekose-servis-tabagi",
    ad: "Çam Ağacı Ekose Servis Tabağı",
    marka: "zensori",
    kategori: "sunum-servis",
    koleksiyonlar: ["yesil-ekose", "yeni-yil-sofrasi"],
    hb: "HBC0000C1FRT0",
    ozet: "Çam ağacı formlu, ahşap çerçeveli, yeşil ekose servis tabağı.",
    aciklama: [
      "Doğal ahşap çerçevesi ve yeşil kareli iç yüzeyiyle çam ağacı formunda bir servis tabağı. Parlak, desenli taban sade bir sofraya hareket katar.",
      "Kahvaltıda ve sezonluk sunumlarda; peynir, kurabiye ya da küçük ikramlıklar için. Boş haliyle de dekoratif bir obje.",
    ],
    ozellikler: [["Malzeme", "Mango ağacı, emaye kaplama"], ["Form", "Çam ağacı"], ["Ölçü", "24,5 × 25,5 cm"]],
    bakim: AHSAP_BAKIM,
    secenekler: ["renk"],
    varyantlar: [{ ty: 1065998240, renk: "Yeşil", fiyat: 1499 }],
  },
  {
    slug: "kar-tanesi-desenli-tabak",
    ad: "Kar Tanesi Desenli Tabak",
    marka: "zensori",
    kategori: "sunum-servis",
    koleksiyonlar: ["yeni-yil-sofrasi"],
    hb: "HBC0000C18ZCV",
    ozet: "Kar tanesi motifli yuvarlak tabak, altın tonlu çerçeve.",
    aciklama: [
      "Kar tanesi desenleriyle süslü yuvarlak bir tabak. Toprak tonlarındaki iç yüzey ve altın renkli çerçeve, mevsime uygun ama abartısız bir şıklık getirir.",
      "Sehpada, konsolda ya da davet sofrasında; mumlar, küçük objeler veya ikramlar için.",
    ],
    ozellikler: [["Malzeme", "Mango ağacı, emaye kaplama"], ["Form", "Yuvarlak"], ["Ölçü", "25,5 cm"]],
    bakim: AHSAP_BAKIM,
    secenekler: ["renk"],
    varyantlar: [{ ty: 1066074676, renk: "Kırmızı", fiyat: 1399 }],
  },
  {
    slug: "sus-desenli-mango-tabak",
    ad: "Süs Desenli Mango Tabak",
    marka: "zensori",
    kategori: "sunum-servis",
    koleksiyonlar: ["yeni-yil-sofrasi"],
    hb: "HBC0000C1RBO8",
    ozet: "Beyaz zemin üzerinde kırmızı süs desenleri, sarı ahşap çerçeve.",
    aciklama: [
      "Beyaz zemin üzerindeki kırmızı süs desenleri mevsimin neşesini sade bir dille taşır. Ahşap kenar çerçevesi tabağa sıcaklık verir.",
      "Yeni yıl sunumlarında, hediye paketlerinin yanında ya da kahvaltı sofrasında. Fotoğraf çekimlerinde fon olarak da kullanılır.",
    ],
    ozellikler: [["Malzeme", "Mango ağacı, emaye kaplama"], ["Form", "Yuvarlak"], ["Ölçü", "21 cm"]],
    bakim: AHSAP_BAKIM,
    secenekler: ["renk"],
    varyantlar: [{ ty: 1066252047, renk: "Kırmızı", fiyat: 1399 }],
  },
  {
    slug: "kurabiye-adam-sunum-tabagi",
    ad: "Kurabiye Adam Sunum Tabağı",
    marka: "zensori",
    kategori: "sunum-servis",
    koleksiyonlar: ["yeni-yil-sofrasi"],
    hb: "HBC0000C1QV4X",
    ozet: "54 × 49 cm, kurabiye adam formlu büyük sunum tabağı.",
    aciklama: [
      "Kurabiye adam formundaki bu büyük tabak, geniş yüzeyiyle sofranın ortasında güçlü bir odak noktası olur. Krem gövde ve altın tonlu kenar.",
      "Kalabalık kahvaltılar, yeni yıl sofraları ya da mutfak adasında sergilemek için. Küçük aksesuar tabaklarından boyuyla ayrışır.",
    ],
    ozellikler: [["Form", "Kurabiye adam"], ["Ölçü", "54 × 49 cm"]],
    bakim: AHSAP_BAKIM,
    secenekler: ["renk"],
    varyantlar: [{ ty: 1065996990, renk: "Krem", fiyat: 3249 }],
  },
  {
    slug: "mango-yildiz-sunum-tabagi",
    ad: "Mango Yıldız Sunum Tabağı",
    marka: "zensori",
    kategori: "sunum-servis",
    koleksiyonlar: ["yeni-yil-sofrasi"],
    hb: "HBC0000C1TKFA",
    ozet: "Yıldız formlu mango ağacı tabak, benekli emaye iç yüzey. İki boy.",
    aciklama: [
      "Yıldız formundaki mango ağacı tabağın iç yüzeyi benekli, parlak bir emaye ile kaplı. Mat toprak tonlu çerçeve ile parlak sır yan yana durur.",
      "Takı, anahtar, doğal taşlar ya da küçük mumlar için. Sehpa, konsol veya komodin üzerinde sade bir odak noktası.",
    ],
    ozellikler: [["Malzeme", "Mango ağacı, emaye kaplama"], ["Form", "Yıldız"], ["Ölçü", "25 cm ya da 28,5 cm"]],
    bakim: AHSAP_BAKIM,
    secenekler: ["boyut"],
    varyantlar: [
      { ty: 1066056383, boyut: "25 cm", renk: "Mavi", fiyat: 1499 },
      { ty: 1066313850, boyut: "28,5 cm", renk: "Gri", fiyat: 1699 },
    ],
  },
  {
    slug: "mango-ahsap-yuvarlak-tabak",
    ad: "Mango Ahşap Yuvarlak Tabak",
    marka: "zensori",
    kategori: "sunum-servis",
    koleksiyonlar: [],
    hb: "HBC0000C1R8HA",
    ozet: "Doğal ahşap üzerinde minimal beyaz çizim. İki boy.",
    aciklama: [
      "Mango ağacının sıcak dokusu, yüzeydeki minimal beyaz çizimle buluşuyor. Ahşap damarları her parçayı farklı kılar.",
      "Küçük boy kahvaltıda peynir ve zeytin için, büyük boy sehpada küçük objeler ya da ikramlar için.",
    ],
    ozellikler: [["Malzeme", "Mango ağacı"], ["Form", "Yuvarlak"], ["Ölçü", "20,5 cm ya da 25 cm"]],
    bakim: AHSAP_BAKIM,
    secenekler: ["boyut"],
    varyantlar: [
      { ty: 1065925486, boyut: "20,5 cm", renk: "Doğal", fiyat: 1100 },
      { ty: 1066067268, boyut: "25 cm", renk: "Doğal", fiyat: 1299 },
    ],
  },
  {
    slug: "mango-ahsap-sapli-kesme-tahtasi",
    ad: "Mango Ahşap Saplı Kesme Tahtası",
    marka: "zensori",
    kategori: "sunum-servis",
    koleksiyonlar: [],
    hb: "HBC0000C1RAZD",
    ozet: "46 × 30 cm, beyaz ağaç figürlü, ipli saplı mango ağacı tahta.",
    aciklama: [
      "Rustik bir kesme ve sunum tahtası. Sol kenardaki beyaz ağaç figürleri ve uçtaki askı ipi sıcak bir görünüm verir.",
      "Mutfakta kesme tahtası, sofrada sunum tahtası, duvarda dekoratif bir obje. Her parçanın ahşap deseni kendine özgüdür.",
    ],
    ozellikler: [["Malzeme", "Mango ağacı"], ["Ölçü", "46 × 30 cm"], ["Detay", "Askı ipi"]],
    bakim: AHSAP_BAKIM,
    secenekler: ["renk"],
    varyantlar: [{ ty: 1065918217, renk: "Doğal", fiyat: 1899 }],
  },
  {
    slug: "ceviz-kesme-tahtasi",
    ad: "Ceviz Kesme ve Sunum Tahtası",
    marka: "zensori",
    kategori: "sunum-servis",
    koleksiyonlar: [],
    ozet: "Tek parça ceviz ağacından, delikli saplı kesme ve sunum tahtası.",
    aciklama: [
      "Tek parça ceviz ağacından kesilmiş bir tahta; birleştirme yeri yoktur. Ceviz damarları her tahtada farklı düşer.",
      "Ekmek, peynir ve şarküteri sunumları için. Delikli sapından asılarak saklanır.",
    ],
    ozellikler: [["Malzeme", "Ceviz ağacı, tek parça"], ["Ölçü", "40 × 18 cm ya da 40 × 20 cm"], ["Gıda teması", "Uygun"]],
    bakim: AHSAP_BAKIM,
    secenekler: ["model"],
    varyantlar: [
      { ty: 1149427168, model: "Açık ton, 40 × 18 cm", renk: "Ceviz", fiyat: 1200 },
      { ty: 1120137178, model: "Koyu ton, 40 × 20 cm", renk: "Ceviz", fiyat: 1200 },
    ],
  },

  // ───────────────────────── Mutfak ─────────────────────────
  {
    slug: "arow-zensori-fluid-yagdanlik",
    ad: "Zensori Fluid Cam Yağdanlık, 1 L",
    marka: "AROW",
    kategori: "mutfak",
    koleksiyonlar: [],
    ozet: "Ölçek çizgili, kulplu, bir litrelik borosilikat cam yağdanlık.",
    aciklama: [
      "AROW'un Zensori serisinden bir litrelik borosilikat cam yağdanlık. Gövdedeki ölçek çizgileri ne kadar yağ kaldığını gösterir; renkli taban ve kapak gövdenin tonuyla eşleşir.",
      "Zeytinyağı, ayçiçek yağı ya da sirke için. Gıdayla temasa uygundur.",
    ],
    ozellikler: [["Malzeme", "Borosilikat cam"], ["Hacim", "1 L"], ["Gıda teması", "Uygun"], ["Model kodu", "TR6512"]],
    bakim: BOROSILIKAT_BAKIM,
    secenekler: ["renk"],
    varyantlar: [
      { ty: 1120947682, renk: "Beyaz", fiyat: 750 },
      { ty: 1120947655, renk: "Gri", fiyat: 750 },
      { ty: 1120947637, renk: "Sarı", fiyat: 750 },
    ],
  },
  {
    slug: "arow-zensori-soft-yagdanlik",
    ad: "Zensori Soft Cam Yağdanlık, 1 L",
    marka: "AROW",
    kategori: "mutfak",
    koleksiyonlar: [],
    ozet: "Yumuşak hatlı gövde, kulplu ve ölçekli borosilikat cam yağdanlık.",
    aciklama: [
      "Zensori serisinin yumuşak hatlı modeli. Kulplu gövde ve ölçek çizgileri günlük kullanımı kolaylaştırır.",
      "Bir litrelik borosilikat cam; gıdayla temasa uygundur. Beyaz, gri ve sarı tonları var.",
    ],
    ozellikler: [["Malzeme", "Borosilikat cam"], ["Hacim", "1 L"], ["Gıda teması", "Uygun"], ["Model kodu", "TR6516"]],
    bakim: BOROSILIKAT_BAKIM,
    secenekler: ["renk"],
    varyantlar: [
      { ty: 1120994923, renk: "Beyaz", fiyat: 750 },
      { ty: 1120994925, renk: "Gri", fiyat: 750 },
      { ty: 1120995564, renk: "Sarı", fiyat: 599 },
    ],
  },
  {
    slug: "arow-zensori-mary-yagdanlik",
    ad: "Zensori Mary Cam Yağdanlık, 1 L",
    marka: "AROW",
    kategori: "mutfak",
    koleksiyonlar: [],
    ozet: "Şeffaf, kulplu ve kapaklı bir litrelik cam yağdanlık.",
    aciklama: [
      "Şeffaf borosilikat camdan, geniş ağızlı ve kulplu bir model. Kolay dolar, kolay temizlenir.",
      "Yağ, sirke ya da limonata için. Gıdayla temasa uygundur.",
    ],
    ozellikler: [["Malzeme", "Borosilikat cam"], ["Hacim", "1 L"], ["Gıda teması", "Uygun"], ["Model kodu", "TR6816"]],
    bakim: BOROSILIKAT_BAKIM,
    secenekler: ["renk"],
    varyantlar: [{ ty: 1120998537, renk: "Şeffaf", fiyat: 500 }],
  },
  {
    slug: "arow-gauzy-cam-yaglik",
    ad: "Gauzy Borosilikat Cam Yağlık",
    marka: "AROW",
    kategori: "mutfak",
    koleksiyonlar: [],
    ozet: "İnce kulplu, renkli tabanlı borosilikat cam yağlık. 350 ve 600 ml.",
    aciklama: [
      "İnce cam kulpu ve renkli tabanıyla hafif görünümlü bir yağlık.",
      "Sofrada zeytinyağı, salata sosu ya da nar ekşisi için. 350 ml ve 600 ml boyları var.",
    ],
    ozellikler: [["Malzeme", "Borosilikat cam"], ["Hacim", "350 ml ya da 600 ml"]],
    bakim: BOROSILIKAT_BAKIM,
    secenekler: ["hacim", "renk"],
    varyantlar: [
      { ty: 1195759297, hacim: "350 ml", renk: "Yeşil", fiyat: 299 },
      { ty: 1200315690, hacim: "350 ml", renk: "Gri", fiyat: 499 },
      { ty: 1200315539, hacim: "600 ml", renk: "Yeşil", fiyat: 549 },
    ],
  },
  {
    slug: "porsima-mantar-kapakli-yaglik",
    ad: "Mantar Kapaklı Cam Yağlık, 500 ml",
    marka: "Porsima",
    kategori: "mutfak",
    koleksiyonlar: [],
    ozet: "Mantar kapaklı, kulplu, şeffaf borosilikat cam yağlık.",
    aciklama: [
      "Mantar kapaklı, kulplu ve ince ağızlı bir yağlık-sirkelik. Şeffaf gövde yağın rengini sofraya taşır.",
      "Yarım litrelik hacmiyle hem tezgâhta hem sofrada kullanılır.",
    ],
    ozellikler: [["Malzeme", "Borosilikat cam, mantar"], ["Hacim", "500 ml"], ["Model kodu", "6517"]],
    bakim: BOROSILIKAT_BAKIM,
    secenekler: ["renk"],
    varyantlar: [{ ty: 1076086464, renk: "Şeffaf", fiyat: 599 }],
  },
  {
    slug: "arow-arista-salata-kurutucu",
    ad: "Arista Sebze ve Salata Kurutucu",
    marka: "AROW",
    kategori: "mutfak",
    koleksiyonlar: [],
    ozet: "Yıkanan yeşillikleri döndürerek kurutan salata kurutucu.",
    aciklama: [
      "Yıkadığınız marul, roka ve otları döndürerek kurutan bir salata kurutucu. Şeffaf kâse ve süzgeç sepetinden oluşur.",
      "Trendyol'da 25 değerlendirmede 4,9 puan almış, mağazanın en çok satan mutfak ürünü (3 Ekim 2026).",
    ],
    ozellikler: [["Malzeme", "Plastik"], ["Model kodu", "TR-6107"]],
    bakim: ["Kullanım ömrünü korumak için elde yıkayın."],
    secenekler: ["renk"],
    varyantlar: [{ ty: 1030898835, renk: "Beyaz", fiyat: 879 }],
  },

  // ───────────────────────── Banyo ─────────────────────────
  {
    slug: "acar-vega-sivi-sabunluk",
    ad: "Vega Seramik Sıvı Sabunluk",
    marka: "ACAR",
    kategori: "banyo",
    koleksiyonlar: [],
    ozet: "Taş dokulu seramik gövde, ahşap etiketli pompalı sabunluk.",
    aciklama: [
      "Taş dokusunu andıran pütürlü seramik gövde ve üzerinde ahşap bir etiket. Banyo tezgâhında ya da mutfak lavabosunun yanında sade durur.",
      "Gri, siyah ve bej üç rengi var.",
    ],
    ozellikler: [["Malzeme", "Seramik"], ["Yükseklik", "17-18 cm"]],
    bakim: SERAMIK_BAKIM,
    secenekler: ["renk"],
    varyantlar: [
      { ty: 922097091, renk: "Gri", fiyat: 750 },
      { ty: 922100468, renk: "Siyah", fiyat: 750 },
      { ty: 957725967, renk: "Bej", fiyat: 750 },
    ],
  },
];
